DROP TABLE IF EXISTS cw_group_therapy CASCADE;
DROP TABLE IF EXISTS cw_treatment CASCADE;
DROP TABLE IF EXISTS cw_patient CASCADE;
DROP TABLE IF EXISTS cw_patient_group CASCADE;
DROP TABLE IF EXISTS cw_doctor CASCADE;
DROP TABLE IF EXISTS cw_faculty CASCADE;
DROP TABLE IF EXISTS cw_disease CASCADE;
DROP TABLE IF EXISTS cw_artifact CASCADE;
DROP TABLE IF EXISTS cw_spell CASCADE;
DROP TABLE IF EXISTS cw_creature CASCADE;
DROP TABLE IF EXISTS cw_user CASCADE;
DROP TABLE IF EXISTS cw_role CASCADE;
DROP TABLE IF EXISTS cw_treatment_history CASCADE;

